FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
COPY client/package*.json ./client/
COPY server/package*.json ./server/
RUN npm ci --workspaces

COPY . .

EXPOSE 3000 5173 9229

CMD ["npm", "run", "dev"]
